run = "./start-dev-fixed.sh"

[deployment]
run = "./start-dev-fixed.sh"

[env]
NODE_ENV = "development"
PORT = "3001"
FRONTEND_PORT = "5173"
BACKEND_PORT = "3001"
VITE_HOST = "0.0.0.0"

[nix]
channel = "stable-24_05"

[[ports]]
localPort = 3001
externalPort = 3001

[[ports]]
localPort = 5173
externalPort = 5173

[packager]
language = "nodejs"

[languages.javascript]
pattern = "**/{*.js,*.jsx,*.ts,*.tsx}"

[gitHubImport]
requiredFiles = [".replit.toml"]