services:
  - type: web
    name: zorax-app
    env: node
    plan: starter
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        fromService:
          type: web
          name: zorax-app
          property: url
    healthCheckPath: /api/health
    autoDeploy: true
    branch: main